melos:
  useRootAsPackage: true
  command:
    version:
      fetchTags: false
      message: "chore: release v{new_version} [skip ci]"
      releaseUrl: true
      changelogs:
        - path: CHANGELOG.md
          packageFilters:
            include:
              - page_turn_animation
    bootstrap:
      usePubspecOverrides: true